# AI-generated (Claude)
require 'json'

Pod::Spec.new do |s|
  s.name           = 'SsrfCore'
  s.version        = '1.0.0'
  s.summary        = 'Subsurface C++ core bridged to React Native'
  s.description    = 'Native module owning the in-memory Subsurface divelog, compiled from the pinned subsurface/ submodule.'
  s.author         = ''
  s.homepage       = 'https://github.com/subsurface/subsurface'
  s.license        = { :type => 'GPL-2.0' }
  s.platforms      = {
    :ios => '16.4',
    :tvos => '16.4'
  }
  s.source         = { git: '' }
  s.static_framework = true

  s.dependency 'ExpoModulesCore'

  # The core subset is materialized into cpp/generated by scripts/vendor-core.mjs
  # before pod install (see the plugin in plugin/withSsrfCore.js). Fail loudly
  # rather than silently building a module with no core in it.
  unless File.directory?(File.join(__dir__, 'cpp/generated/core'))
    raise 'ssrf-core: cpp/generated is missing - run `node modules/ssrf-core/scripts/vendor-core.mjs`'
  end

  s.pod_target_xcconfig = {
    # Pods build as framework targets here, so Swift reaches the Objective-C++
    # facade through the generated umbrella header (public_header_files below),
    # not through a bridging header - those are rejected in framework targets.
    'DEFINES_MODULE' => 'YES',
    # The Subsurface core requires C++17 or newer; keep libc++ to match RN.
    'CLANG_CXX_LANGUAGE_STANDARD' => 'c++20',
    'CLANG_CXX_LIBRARY' => 'libc++',
    'HEADER_SEARCH_PATHS' => [
      '"$(PODS_TARGET_SRCROOT)/cpp"',
      '"$(PODS_TARGET_SRCROOT)/cpp/generated"',
      '"$(PODS_TARGET_SRCROOT)/cpp/generated/core"',
      # Stand-ins for the Qt headers a few core files include for a macro.
      '"$(PODS_TARGET_SRCROOT)/cpp/shim/include"',
      # libxml2 ships with the SDK; libxslt headers arrive in task 04.
      '"$(SDKROOT)/usr/include/libxml2"',
    ].join(' '),
    # SUBSURFACE_MOBILE keeps the desktop-only code paths out of the core.
    # ssrf-stdlib-compat.h supplies includes upstream gets through Qt.
    'OTHER_CPLUSPLUSFLAGS' => '-DSUBSURFACE_MOBILE -include "$(PODS_TARGET_SRCROOT)/cpp/shim/include/ssrf-stdlib-compat.h"',
  }

  # libxml2 and sqlite3 are in the iOS SDK. libxslt has a .tbd in the SDK but no
  # headers - task 04 vendors those.
  s.libraries = 'xml2', 'sqlite3', 'xslt', 'z'

  # Objective-C/Swift glue lives in ios/, portable C++ in cpp/. The podspec sits
  # at the module root so CocoaPods can reach both (file patterns must not
  # escape the pod root). tests/ is deliberately excluded: it is host-only.
  s.source_files = 'ios/**/*.{h,m,mm,swift}', 'cpp/*.{h,cpp}', 'cpp/shim/**/*.{h,cpp}', 'cpp/generated/**/*.{h,c,cpp}'

  # Only the Objective-C facade may enter the umbrella header: everything under
  # cpp/ is C++ and would break the module map for Swift/Objective-C consumers.
  s.public_header_files = 'ios/**/*.h'
  s.private_header_files = 'cpp/**/*.h'
end
