// AI-generated (Claude)
//
// Materializes the compilable Subsurface core subset into `cpp/generated/`.
//
// The `subsurface/` submodule is read-only, and CocoaPods file patterns cannot
// escape the pod root, so the subset is copied into the module before every
// native build. Copy -> patch -> overlay, in that order:
//
//   1. copy the core headers and the translation units named in
//      `core-subset.mjs`, plus the libdivecomputer headers (enums only)
//   2. apply `patches/*.patch` to remove the Qt tails from core headers
//   3. overlay `cpp/shim/override/` so our Qt-free replacements win over the
//      core headers of the same name (quoted includes resolve next to the
//      including file, so replacing the copy is the only reliable overlay)
//
// `cpp/generated/` is git-ignored and fully reproducible; never edit it.

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
	CORE_HEADER_GLOBS,
	CORE_SOURCES,
	LIBDC_HEADER_DIR,
	PATCHES,
	XSLT_DIR,
} from '../core-subset.mjs';

const moduleRoot = path.resolve(fileURLToPath(import.meta.url), '../..');
const repoRoot = path.resolve(moduleRoot, '../..');
const submodule = path.join(repoRoot, 'subsurface');
const generated = path.join(moduleRoot, 'cpp/generated');
const xsltOut = path.join(moduleRoot, 'resources/xslt');

function fail(message) {
	console.error(`[vendor-core] ${message}`);
	process.exit(1);
}

function copyFile(from, to) {
	fs.mkdirSync(path.dirname(to), { recursive: true });
	fs.copyFileSync(from, to);
}

// Expands the `dir/*.ext` globs of CORE_HEADER_GLOBS. Deliberately minimal:
// the manifest only ever needs a single trailing wildcard.
function expandGlob(glob) {
	const dir = path.dirname(glob);
	const pattern = path.basename(glob);
	if (!pattern.startsWith('*')) return [glob];
	const suffix = pattern.slice(1);
	return fs
		.readdirSync(path.join(submodule, dir))
		.filter((name) => name.endsWith(suffix))
		.map((name) => `${dir}/${name}`);
}

// libdivecomputer ships version.h as an autotools template. We only need the
// enums and the DC_VERSION_CHECK macro, so the three numbers are lifted
// straight out of configure.ac rather than running configure.
function generateLibdcVersionHeader(outDir) {
	const configure = fs.readFileSync(path.join(submodule, 'libdivecomputer/configure.ac'), 'utf8');
	const number = (which) => {
		const match = configure.match(new RegExp(`m4_define\\(\\[dc_version_${which}\\],\\[(\\d+)\\]\\)`));
		if (!match) fail(`cannot read dc_version_${which} from libdivecomputer/configure.ac`);
		return match[1];
	};
	const [major, minor, micro] = ['major', 'minor', 'micro'].map(number);
	const suffix = configure.match(/m4_define\(\[dc_version_suffix\],\[([^\]]*)\]\)/)?.[1] ?? '';
	const version = suffix ? `${major}.${minor}.${micro}-${suffix}` : `${major}.${minor}.${micro}`;

	const template = fs.readFileSync(
		path.join(submodule, LIBDC_HEADER_DIR, 'version.h.in'),
		'utf8'
	);
	const header = template
		.replace('@DC_VERSION@', version)
		.replace('@DC_VERSION_MAJOR@', major)
		.replace('@DC_VERSION_MINOR@', minor)
		.replace('@DC_VERSION_MICRO@', micro);
	fs.writeFileSync(path.join(outDir, 'version.h'), header);
	return version;
}

// core/version.cpp includes "ssrf-version.h", which upstream's CMake generates
// from scripts/get-version.sh. We are not using their CMake, so generate the
// same header here from the same script, run inside the submodule so it
// describes the pinned core and not this repository.
function generateSsrfVersionHeader(outDir) {
	const describe = (arg) =>
		execFileSync('bash', [path.join(submodule, 'scripts/get-version.sh'), ...(arg ? [arg] : [])], {
			cwd: submodule,
			encoding: 'utf8',
		}).trim();

	const version = describe();
	const version4 = describe('4');
	fs.writeFileSync(
		path.join(outDir, 'ssrf-version.h'),
		'// Generated by modules/ssrf-core/scripts/vendor-core.mjs - do not edit.\n' +
			'#pragma once\n' +
			`#define CANONICAL_VERSION_STRING "${version}"\n` +
			`#define CANONICAL_VERSION_STRING_4 "${version4}"\n`
	);
	return version;
}

function overlay(dir, into) {
	if (!fs.existsSync(dir)) return 0;
	let count = 0;
	for (const name of fs.readdirSync(dir)) {
		const from = path.join(dir, name);
		if (fs.statSync(from).isDirectory()) {
			count += overlay(from, path.join(into, name));
			continue;
		}
		copyFile(from, path.join(into, name));
		count++;
	}
	return count;
}

// Fingerprint of every input that can change the generated tree. Xcode re-reads
// the Expo config from a build phase while compilation is already running, so
// this script must be a no-op when nothing changed - re-materializing the tree
// underneath the compiler races it.
function inputFingerprint(pinned) {
	const parts = [pinned];
	const stat = (file) => {
		const s = fs.statSync(file);
		parts.push(`${path.relative(moduleRoot, file)}:${s.size}:${s.mtimeMs}`);
	};
	stat(path.join(moduleRoot, 'core-subset.mjs'));
	for (const patch of PATCHES) stat(path.join(moduleRoot, 'patches', patch));
	const walk = (dir) => {
		if (!fs.existsSync(dir)) return;
		for (const name of fs.readdirSync(dir).sort()) {
			const full = path.join(dir, name);
			fs.statSync(full).isDirectory() ? walk(full) : stat(full);
		}
	};
	walk(path.join(moduleRoot, 'cpp/shim/override'));
	return parts.join('\n');
}

if (!fs.existsSync(path.join(submodule, 'core/dive.cpp')))
	fail('subsurface/ submodule is empty - run `git submodule update --init --recursive`');
if (!fs.existsSync(path.join(submodule, LIBDC_HEADER_DIR)))
	fail('subsurface/libdivecomputer is empty - run `git submodule update --init --recursive` in subsurface/');

// The submodule's checked-out commit, which the stamp is keyed on. A cloud
// build (EAS) may unpack the submodule's *files* without its git metadata, so
// the pin recorded in CORE_MANIFEST.md is the fallback - the manifest is the
// record of what is vendored anyway, and a build that cannot ask git is still
// building exactly the tree it was handed.
function pinnedCommit() {
	try {
		return execFileSync('git', ['-C', submodule, 'rev-parse', 'HEAD'], {
			encoding: 'utf8',
			stdio: ['ignore', 'pipe', 'ignore'],
		}).trim();
	} catch {
		const manifest = fs.readFileSync(path.join(moduleRoot, 'cpp/CORE_MANIFEST.md'), 'utf8');
		const match = /`subsurface\/` submodule \| `([0-9a-f]+)`/.exec(manifest);
		if (!match) fail('cannot determine the pinned core commit (no git, no manifest entry)');
		return match[1];
	}
}

const pinned = pinnedCommit();
const stampFile = path.join(generated, '.vendor-stamp');
const fingerprint = inputFingerprint(pinned);

if (
	fs.existsSync(stampFile) &&
	fs.readFileSync(stampFile, 'utf8') === fingerprint &&
	fs.existsSync(xsltOut)
) {
	console.log(`[vendor-core] up to date (core ${pinned.slice(0, 9)})`);
	process.exit(0);
}

// Build into a scratch directory and swap it in, so the tree is never
// half-populated even if the build is watching it.
const staging = `${generated}.tmp`;
fs.rmSync(staging, { recursive: true, force: true });

const headers = CORE_HEADER_GLOBS.flatMap(expandGlob);
for (const rel of [...headers, ...CORE_SOURCES]) {
	const from = path.join(submodule, rel);
	if (!fs.existsSync(from)) fail(`missing in submodule: ${rel}`);
	copyFile(from, path.join(staging, rel));
}

const libdcOut = path.join(staging, 'libdivecomputer');
fs.mkdirSync(libdcOut, { recursive: true });
for (const name of fs.readdirSync(path.join(submodule, LIBDC_HEADER_DIR))) {
	if (!name.endsWith('.h')) continue;
	copyFile(path.join(submodule, LIBDC_HEADER_DIR, name), path.join(libdcOut, name));
}
const libdcVersion = generateLibdcVersionHeader(libdcOut);
const coreVersion = generateSsrfVersionHeader(path.join(staging, 'core'));

for (const patch of PATCHES) {
	const file = path.join(moduleRoot, 'patches', patch);
	if (!fs.existsSync(file)) fail(`missing patch: patches/${patch}`);
	try {
		execFileSync('patch', ['-p1', '--no-backup-if-mismatch', '-i', file], {
			cwd: staging,
			stdio: 'pipe',
		});
	} catch (error) {
		fail(
			`patch failed: patches/${patch}\n` +
				`${error.stdout ?? ''}${error.stderr ?? ''}\n` +
				'The submodule pin probably moved - refresh the patch against the new core.'
		);
	}
}

// The stylesheets are data, not code, so they go to resources/ rather than into
// the compiled tree - the podspec ships that directory as a resource bundle.
// Same staging dance as above: swapped in whole, never half-written.
const xsltStaging = `${xsltOut}.tmp`;
fs.rmSync(xsltStaging, { recursive: true, force: true });
fs.mkdirSync(xsltStaging, { recursive: true });
const stylesheets = fs
	.readdirSync(path.join(submodule, XSLT_DIR))
	.filter((name) => name.endsWith('.xslt') || name.endsWith('.xsl'));
if (stylesheets.length === 0) fail(`no stylesheets in subsurface/${XSLT_DIR}`);
for (const name of stylesheets)
	copyFile(path.join(submodule, XSLT_DIR, name), path.join(xsltStaging, name));
fs.rmSync(xsltOut, { recursive: true, force: true });
fs.renameSync(xsltStaging, xsltOut);

const overlaid = overlay(path.join(moduleRoot, 'cpp/shim/override'), path.join(staging, 'core'));
fs.writeFileSync(stampFile.replace(generated, staging), fingerprint);

fs.rmSync(generated, { recursive: true, force: true });
fs.renameSync(staging, generated);

console.log(
	`[vendor-core] ${CORE_SOURCES.length} sources, ${headers.length} headers, ` +
		`${PATCHES.length} patches, ${overlaid} overrides, ${stylesheets.length} stylesheets; ` +
		`core ${pinned.slice(0, 9)} (${coreVersion}), libdivecomputer ${libdcVersion}`
);
